# Generated by Django 4.0.4 on 2022-08-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
